# Generated by Django 5.0.6 on 2024-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recepcionistas',
            fields=[
                ('IDrecepcionista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('contraseña', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('IDusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
